import test from 'node:test'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {fundraisingRequestSchema,fundraisingResultSchema} from '../shared/crypto-fundraising.js'
import {privateServiceAllows} from '../shared/private-services.js'
import {generateFundraising,fundraisingQueries} from '../server/src/services/crypto-fundraising.js'
import {fundraisingHandler} from '../server/src/fundraising-route.js'
const input=fundraisingRequestSchema.parse({schema:'zeroscout.crypto-fundraising.request',schemaVersion:'1.0.0',requestId:'fixture_001',query:'Example historical raises',from:'2022-01-01',to:'2022-12-31'})
const quote='Example announced a Seed funding round on October 13, 2022, raising $10 million led by Investor One. It builds on Ethereum.'
const source={id:'S1',url:'https://example.com/announcement',title:'Funding',publishedAt:'2022-10-13',retrievedAt:new Date().toISOString(),contentSha256:createHash('sha256').update(quote).digest('hex'),text:quote}
const candidate={project:'Example',category:'company-round',round:'Seed',announcedAt:'2022-10-13',amountReported:'$10 million',valuationReported:null,investors:['Investor One'],chains:['Ethereum'],status:'announced',evidence:[{sourceId:'S1',quote,fields:['project','category','round','announcedAt','amountReported','investors','chains','status']}]}
const retrieve=async()=>({sources:[source],gaps:[]})
const complete=(records:unknown[])=>async()=>({content:JSON.stringify({records,dataGaps:[]}),provider:'fixture'})
test('schema rejects extra endpoints, invalid dates, reversed ranges and unbounded output',()=>{for(const patch of [{url:'http://localhost'},{from:'2022-02-30'},{from:'2023-01-01'},{to:'9999-01-01'},{limit:21},{categories:['company-round','company-round']}])assert.equal(fundraisingRequestSchema.safeParse({...input,...patch}).success,false);assert.equal(fundraisingQueries(input).length,2)})
test('dedicated key isolates fundraising from existing services',()=>{const path='/api/integrations/crypto-fundraising';assert.equal(privateServiceAllows('crypto-fundraising',path),true);for(const service of ['all-private','lp-intelligence','agreement-intelligence','smart-contract-auditing'])assert.equal(privateServiceAllows(service,path),false);assert.equal(privateServiceAllows('crypto-fundraising','/api/integrations/smart-contract-audit'),false)})
test('source-linked historical output preserves units and declares partial coverage',async()=>{const r=await generateFundraising(input,new AbortController().signal,{retrieve,complete:complete([candidate])});assert(fundraisingResultSchema.safeParse(r).success);assert.equal(r.records.length,1);assert.equal(r.coverage.complete,false);assert.equal(r.coverage.totalHistoricalRecords,null);assert.equal(r.records[0].amountReported,'$10 million');assert(!('text' in r.sources[0]));assert.equal(r.records[0].verification,'ai-extracted-citations-matched')})
test('fabricated quote, amount, investor and missing field citations are discarded',async()=>{for(const patch of [{evidence:[{...candidate.evidence[0],quote:'invented text'}]},{amountReported:'$100 million'},{investors:['Unknown VC']},{evidence:[{...candidate.evidence[0],fields:['project']}]}]){const r=await generateFundraising(input,new AbortController().signal,{retrieve,complete:complete([{...candidate,...patch}])});assert.equal(r.records.length,0);assert.equal(r.coverage.discarded,1)}})
test('duplicates, undated, out-of-range, planned and excluded-category records do not pass',async()=>{for(const patch of [{announcedAt:null},{announcedAt:'2021-10-13'},{status:'planned'}]){const r=await generateFundraising(input,new AbortController().signal,{retrieve,complete:complete([{...candidate,...patch}])});assert.equal(r.records.length,0)}const r=await generateFundraising(input,new AbortController().signal,{retrieve,complete:complete([candidate,candidate])});assert.equal(r.records.length,1);assert.equal(r.coverage.discarded,1);const filtered=await generateFundraising({...input,categories:['public-token-sale']},new AbortController().signal,{retrieve,complete:complete([candidate])});assert.equal(filtered.records.length,0)})
test('no retrieved sources cannot trigger model hallucinations',async()=>{let called=false;const r=await generateFundraising(input,new AbortController().signal,{retrieve:async()=>({sources:[],gaps:[]}),complete:async()=>{called=true;throw Error()}});assert.equal(called,false);assert.equal(r.records.length,0);assert(r.dataGaps.some(s=>s.includes('never occurred')))})
test('retrieval/model failure and invalid outputs fail rather than returning historical facts',async()=>{await assert.rejects(generateFundraising(input,new AbortController().signal,{retrieve:async()=>{throw Error('outage')},complete:complete([])}));await assert.rejects(generateFundraising(input,new AbortController().signal,{retrieve,complete:async()=>({content:'not json',provider:'fixture'})}));const abort=new AbortController();abort.abort();await assert.rejects(generateFundraising(input,abort.signal,{retrieve,complete:complete([])}))})
test('endpoint rejects anonymous callers and unconfigured provider without invoking inference',async()=>{let status=0,called=false;const res={setHeader(){},status(n:number){status=n;return this},json(){return this}};const gen=async()=>{called=true;throw Error()};await fundraisingHandler(gen,()=>undefined)({body:input} as any,res as any);assert.equal(status,401);await fundraisingHandler(gen,()=>({id:'key',name:'test',partner:'Grail'}),()=>false)({body:input} as any,res as any);assert.equal(status,503);assert.equal(called,false)})
